name: Horizons
description: Horizons template for Jekyll
paginate: 10
baseurl: 'http://meilke.github.io/adventgemeinde-spandau-preview'
gems: [jekyll-paginate, contentful]

topic_src_dir: '_src'
data_dir: '_data'
data_file: 'contentful/spaces/spandau.yaml'

contentful:
  spaces:
    - spandau:
        space: space-id
        access_token: access-token
        client_options:
          api_url: 'preview.contentful.com'
