title: Adventgemeinde Berlin-Spandau
email: info@adventgemeinde-spandau.de
baseurl: ""
url: "http://www.adventgemeinde-spandau.de"
twitter_username: jekyllrb
github_username:  jekyll

markdown: kramdown

contentful:
  spaces:
    - spandau:
        space: my-space
        access_token: my-token
        client_options:
          api_url: 'preview.contentful.com'
