name: Horizons
description: Horizons template for Jekyll
paginate: 10
baseurl: 'http://meilke.github.io/adventgemeinde-spandau-preview'
gems: [jekyll-paginate, contentful]

contentful:
  spaces:
    - spandau:
        space: space-id
        access_token: access-token
        client_options:
          api_url: 'preview.contentful.com'
